support stage3 without busybox
reinstate the standalone mv hack

diff --git a/to-gentoo b/to-gentoo
--- a/to-gentoo
+++ b/to-gentoo
@@ -135,8 +135,33 @@ fi
 
 
 # using static busybox from Gentoo to run mv
-cp "${GENTOO}/bin/busybox" /tmp
-MYMV="/tmp/busybox mv"
+if [ -e "${GENTOO}/bin/busybox" ]; then
+  cp "${GENTOO}/bin/busybox" /tmp
+  MYMV="/tmp/busybox mv"
+elif [ -e /bin/mv ]; then
+  echo "Creating a working standalone mv"
+  MV=$(mktemp -d)
+  cp /bin/mv "${MV}"
+  ldd /bin/mv | sed "s/\t//" | while read f ; do
+    g=$(echo "${f}" | cut -d' ' -f 3)
+    f=$(echo "${f}" | cut -d' ' -f 1)
+    if [ "${f}" == "linux-vdso.so.1" ] ||
+       [ "${f}" == "linux-gate.so.1" ]; then
+      continue
+    fi
+
+    if [ -e "${f}" ]; then
+      cp "${f}" "${MV}"
+    elif [ -e "/${g}" ]; then
+      cp "${g}" "${MV}"
+    fi
+  done
+  # glibc, musl are supported here
+  MYMV="${MV}/ld-*-x86?64.so.? --library-path ${MV} ${MV}/mv"
+else
+  echo "missing /bin/mv" >&2
+  exit 1
+fi
 # test it
 touch /tmp/a
 ${MYMV} /tmp/a /tmp/b
